### ISSUE TITLE
Found this on Reddit, I thought it or something like it, might be what is missing from the Introduction.

### ISSUE THREAD

**Issue by tharple** [casey/iota#4]
IOTA is a scalable, decentralized, feeless, modular, open-source distributed ledger protocol that goes 'beyond blockchain' through its core invention of the blockless ‘Tangle’. The IOTA Tangle is a quantum-resistant Directed Acyclic Graph (DAG). IOTA has no fees to transact and no scaling limitations; network transaction speed grows with activity. IOTA grows via transactors, not miners / stakers, thus avoiding centralization.

IOTA is aiming to be the backbone of the emerging machine-to-machine (m2m) economy of the Internet-of-Things (IoT), data integrity, micro-/nano- payments, and other cases where a scalable decentralized system adds value.

Felix Unger: You should never assume, because when you assume, you make an ass of "u" and "me."

**Comment by casey** [comment]
Thank you for opening this issue! I think I refute all of these points in the article.

**Comment by tharple** [comment]
I guess I over shoot my point.
WTF is IOTA. is it an  *acronyms and initializations? What do the letters
stand for. Why do I care about what the remainder of your articles says if
you don't tell me in the introduction what IOTA is.*
*Why did I immediately need to leave your article in order to find this
out.*
*Peace out good luck*



Terry Harple
Merrimack NH

**Comment by casey** [comment]
Oh, sorry, I thought you were presenting those things as the truth and criticizing the article for not agreeing with IOTAs self description.

**Comment by casey** [comment]
I think you make a valid point, I'll add a introduction to the article.
