### ISSUE TITLE
This "article" is a joke.

### ISSUE THREAD

**Issue by eeconomy** [casey/iota#6]
This article is completely ridiculous.  There are some particles of truth spread over a sea jealousy.  6 of your references are tweets which don't amount to much more than opinion.

You knock IOTA for using quantum secure cryptography, even though quantum computers do not exist yet.  Talk about a contrived argument.  There is always going to be a trade off.  We get a quantum secure coin. 
 Currently, the trade-off is that dumb people should not be using iota.  There are ways to solve the issue in the future, so that even dumb people cannot stub their toes.

**Comment by casey** [comment]
Thank you for the feedback! I disagree. I think that technology needs to cater to the needs of users, not the other way around.

**Comment by eeconomy** [comment]
Luckily it does not have to cater to you then.

**Comment by casey** [comment]
You are highly perceptive, I am not a user of IOTA 🤣
